name: bus_tracker
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 2.0.0
  google_maps_flutter: 0.5.21+7
  carousel_pro: ^1.0.0
  permission_handler: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/